### PR TITLE
Test cellranger with dual genome (K2/2)

### LINKED ISSUE #26: cellranger-analysis module: potential issue with dual genome reference
## What analysis module should be updated and why?

There might be an issue with the `cellranger-analysis` module when using dual genome reference. 

From our discussion with @sharonfreshour:

- The dual reference runs CellRanger's metrics include some that are specific to either the human or the mouse genomes used and those are labeled by CellRanger based on the reference name. For example, when the `summarize-cellranger-results.py` script is looking for a column named `mm10 ...`, it should be looking for a column named `GRCm39 ...` based on how CellRanger itself will name the metrics columns for the new GRCm39 reference.
 

## What changes need to be made? Please provide enough detail for another participant to make the update.

We will not make any changes for the moment.

### PR DESCRIPTION
**Pull request by AntoniaChroni**
# Purpose/implementation Section

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## What GitHub issue does your pull request address?

Closes #26.

## Directions for reviewers 
Tell potential reviewers what kind of feedback you are soliciting.

### Which areas should receive a particularly close look?

 
- [ ] Run the `cellranger-analysis` module as described in the `README` file by using the file path to the `GRCh38ANDGRCm39` genome reference.

## Documentation Checklist

- [x] This analysis module has a `README` and it is up to date.
- [x] The analytical code is documented and contains comments.

### CODE REVIEW

**Review by sharonfreshour — CHANGES_REQUESTED** [review]
The test ran properly with  the dual genome up until the summarize_cellranger_results.py script is run. I will share the error file with you.

The metrics_summary.csv files from cellranger have some different column names for a dual genome run (i.e. some column names are preceded by GRCh38 and GRCm39). If the optional --genome flag is not used with the summarize_cellranger_results.py script then the script will look for some column names that are not present in the dual genome files.

Perhaps this could be remedy by specifying that if the user has a dual genome, then they must use the --genome flag. However, there are two possible issues that might raise (1) the script will only report the metrics for the --genome specified (e.g. if GRCm39 is specified, GRCh38 metrics won't be in the summary file) and (2) if the user has a dual genome that uses anything besides GRCh38ANDGRCm39, the current script will break regardless, since GRCh38 and GRCm39 options within the script are hard coded.

**Comment by AntoniaChroni** [comment]
@CodyRamirez The `j1.sh` job that conducts the alignment per each library runs smoothly and individual files are generated as expected. However, there is inconsistency in the column names generated by dual genome samples and the name column specified in the `summarize_cellranger_results.py` script. This leads to failure of the `j2.sh` job generating the summary metrics table for all libraries, `QC_Summary_CellRanger_Report.tsv` file.

**Comment by AntoniaChroni** [comment]
> The test ran properly with the dual genome up until the summarize_cellranger_results.py script is run. I will share the error file with you.
> 
> The metrics_summary.csv files from cellranger have some different column names for a dual genome run (i.e. some column names are preceded by GRCh38 and GRCm39). If the optional --genome flag is not used with the summarize_cellranger_results.py script then the script will look for some column names that are not present in the dual genome files.
> 
> Perhaps this could be remedy by specifying that if the user has a dual genome, then they must use the --genome flag. However, there are two possible issues that might raise (1) the script will currently only report the metrics for the --genome specified (e.g. if GRCm39 is specified, GRCh38 metrics won't be in the report file) and (2) if the user has a dual genome that uses anything besides GRCh38ANDGRCm39, the current summarize_cellranger_results.py script will break regardless, since GRCh38 and GRCm39 options within the script are hard coded.

@sharonfreshour I think the issue is that the `-- genome` flag was missing. This has been added now here 1bbbd2fd63b6c4af9a69c80ce5358b7476a5fbf0. Please test again by running only `j2.sh` and let me know how it goes.

**Comment by AntoniaChroni** [comment]
@sharonfreshour I added the [parameter genome_name_cellranger](https://github.com/stjude-dnb-binfcore/sc-rna-seq-snap/pull/37/commits/7f2be99e631b092dabc34ca4e139f3f6361511a8).

**Review by sharonfreshour — APPROVED** [review]
j2.sh now runs and QC_Summary_CellRanger_Report.tsv looks correct

**Pull request merged**
